function [S_int,var_0] = solve_system_threshold_3D(S,T_s,var_0,t,J,P)
% obtain displacement of mesh according to the force generated by the
% membrane and the force generated by polymerization of actin (if
% actin_dym>0)
    delta_t = P.delta_t;
    count = 0;
    var_00 = var_0;
    

    [S_int,var_0] = solve_system_3D(S,T_s,var_00,t,delta_t,J,P); 
    d_max = max(sqrt(dot(S_int-S,S_int-S,2)));
%     check if the diplacement of the vertices is less than d_tol,
%     otherwise half the time interval
    while d_max >  P.d_max_int
        delta_t = delta_t/2;
        [S_int,var_0] = solve_system_3D(S,T_s,var_00,t,delta_t,J,P);
        d_max = max(sqrt(dot(S_int-S,S_int-S,2)));
        count = count+1;   
    end
    disp(count)
    if count > 0
        for j=1:(2^count-1)
            [S_int,var_0] = solve_system_3D(S_int,T_s,var_0,t+j*delta_t,delta_t,J,P);
        end
    end
end